# Generated by Django 4.2.7 on 2023-11-02 20:19

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='media/thumbnails'),
        ),
    ]
