# Generated by Django 4.2.7 on 2023-11-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_profile_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
